# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6b335367b6a052d21e4d72d362f1ac305c79c35a1c1f5cab58959a4e9ccacb8b67267ffd9616ef6d7a3726393900053292eafaae408c0a7aae7b435a2428ddf

test:
  secret_key_base: 84c6c0e08a6a94c4cf611a83aa0281b9189730d270e4a1ad4ecc9a1f0b3d327cd70471e1be472d8d5046448e67e014f9a42fca8cb57c17c38b5868964c6d5b3f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
